### ALIASES ###
alias v "vim"
alias gb "git branch"
alias gd "git diff"
alias es "exec $SHELL"
alias gca "git add -A && git commit -m"
alias gcm "git checkout master"
alias gp "git pull"
alias gs "git status"
alias ipy "ipython"
alias py "python"
alias tf "terraform"