#!/bin/bash

### SHELL ###

# Install Homebrew

brew --version &> /dev/null || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Install jq
brew list jq &> /dev/null || brew install jq

# Install the_silver_searcher
brew list the_silver_searcher &> /dev/null || brew install the_silver_searcher

# Link zshrc
ln -fs $(pwd)/zshrc ~/.zshrc

# Link agignore
ln -fs $(pwd)/agignore ~/.agignore

### GIT ###

# Link gitconfig
ln -fs $(pwd)/gitconfig ~/.gitconfig

### VIM ###

# Install Pathogen 
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install Pathogen Plugins
dir=~/.vim/bundle/vim-go
ls $dir &> /dev/null || git clone https://github.com/fatih/vim-go.git $dir

dir=~/.vim/bundle/ctrlp.vim
ls $dir &> /dev/null || git clone https://github.com/ctrlpvim/ctrlp.vim.git $dir

# Link vimrc
ln -fs $(pwd)/vimrc ~/.vimrc

### RUBY ###

ln -fs $(pwd)/gemrc ~/.gemrc
brew list rbenv &> /dev/null || brew install rbenv
