#!/usr/bin/env bash

### This script assumes that git has been installed! ###

### Start vim ###
echo 'Setting up vim'

# Download molokai color scheme for vim #
if ! [ -e ~/.vim/colors ]; then
  git clone git@github.com:tomasr/molokai.git /tmp/molokai
  mv /tmp/molokai/colors/molokai.vim ~/.vim/colors
  rm -rf /tmp/molokai
else
  echo 'Molokai color scheme already installed'
fi

# Download Vundle plugin manager for vim #
if ! [ -e ~/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
else
  echo 'Vundle plugin manager already installed'
fi

### End vim ###
